# Default values for database chart
image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15-alpine"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: ""

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
postgresql:
  database: "backend_api"
  username: "backend-api"
  password: "password"  # Should be overridden in environment-specific values
