# Staging environment values for backend-api
replicaCount: 2

image:
  repository: "nginxdemos/hello"
  tag: latest

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Staging-specific environment variables
env:
  NODE_ENV: staging
  PORT: "3000"
  DATABASE_URL: postgresql://backend-api:staging-password@database:5432/backend_api_staging
  REDIS_URL: redis://redis:6379
  JWT_SECRET: staging-jwt-secret-change-me
  LOG_LEVEL: debug
