# Default values for backend-api chart
replicaCount: 3

image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "18-alpine"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

# Environment-specific configuration
env:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_URL: postgresql://backend-api:password@database:5432/backend_api
  REDIS_URL: redis://redis:6379
  JWT_SECRET: changeme-in-production
